apiVersion: v1
kind: Service
metadata:
  name: ceibo-core-frontend
  labels:
    {{- include "ceibo-core.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: ceibo-core
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}
